"""
This type stub file was generated by pyright.
"""

"""Python 2/3 compatibility wrappers.

This module contains imports and functions that help mask Python 2/3
compatibility issues.
"""

def TemporaryFile(
    mode=..., encoding=..., suffix=..., prefix=..., dir=...
):  # -> IO[Any]:
    """
    Provide py2/3 compatability for TemporaryFile.

    Redefining TemporaryFile from py27 because it doesn't support the
    `encoding` parameter.
    """
    ...
