class Range:
    invert: bool
    start: float | int
    end: float | int

    def __init__(self, spec: str | int | Range = ...) -> None: ...
    def __new__(cls, spec: str | int | Range = ...) -> Range: ...
    def match(self, value: float | int) -> bool: ...
    def __contains__(self, value): ...
    def __str__(self) -> str:
        """Human-readable range specification."""
        ...
    def __repr__(self):  # -> str:
        """Parseable range specification."""
        ...
    @property
    def violation(self):  # -> str:
        """Human-readable description why a value does not match."""
        ...
