"""
This type stub file was generated by pyright.
"""

import collections

class Range(collections.namedtuple("Range", "invert start end")):
    """Represents a threshold range.

    The general format is "[@][start:][end]". "start:" may be omitted if
    start==0. "~:" means that start is negative infinity. If `end` is
    omitted, infinity is assumed. To invert the match condition, prefix
    the range expression with "@".

    See
    http://nagiosplug.sourceforge.net/developer-guidelines.html#THRESHOLDFORMAT
    for details.
    """

    def __new__(cls, spec=...):  # -> Self@Range:
        """Creates a Range object according to `spec`.

        :param spec: may be either a string, an int, or another
            Range object.
        """
        ...
    def match(self, value):
        """Decides if `value` is inside/outside the threshold.

        :returns: `True` if value is inside the bounds for non-inverted
            Ranges.

        Also available as `in` operator.
        """
        ...
    def __contains__(self, value): ...
    def __str__(self) -> str:
        """Human-readable range specification."""
        ...
    def __repr__(self):  # -> str:
        """Parseable range specification."""
        ...
    @property
    def violation(self):  # -> str:
        """Human-readable description why a value does not match."""
        ...
