def guarded(original_function=..., verbose: bool = ...): ...

class Runtime:
    instance = ...
    check = ...
    _verbose = ...
    timeout = ...
    logchan = ...
    output = ...
    stdout = ...
    exitcode = ...
    def __new__(cls): ...
    def __init__(self) -> None: ...
    @property
    def verbose(self): ...
    @verbose.setter
    def verbose(self, verbose): ...
    def run(self, check): ...
    def execute(self, check, verbose=..., timeout=...): ...
    def sysexit(self): ...
