from typing import List, Literal

from nagiosplugin.result import Results

class Summary:
    def ok(self, results: Results) -> str: ...
    def problem(self, results: Results) -> str: ...
    def verbose(self, results: Results) -> List[str]: ...
    def empty(self) -> Literal["no check results"]: ...
